#Shape Manipulation

You have already seen during the creation of a two-dimensional array how it is possible to convert a onedimensional array into a matrix, thanks to the reshape() function.

In [ ]:
import numpy as np
a = np.random.random(12)
a

array([0.69699999, 0.40398593, 0.51616774, 0.09248855, 0.00874348,
       0.47961266, 0.82526615, 0.07383346, 0.23389424, 0.76303897,
       0.39756264, 0.23745441])

In [ ]:
A = a.reshape(3, 4)
A

array([[0.69699999, 0.40398593, 0.51616774, 0.09248855],
       [0.00874348, 0.47961266, 0.82526615, 0.07383346],
       [0.23389424, 0.76303897, 0.39756264, 0.23745441]])

In [ ]:
a

array([0.69699999, 0.40398593, 0.51616774, 0.09248855, 0.00874348,
       0.47961266, 0.82526615, 0.07383346, 0.23389424, 0.76303897,
       0.39756264, 0.23745441])

The reshape() function returns a new array and therefore it is useful to create new objects. However if you want to modify the object by modifying the shape, you have to assign a tuple containing the new dimensions directly to its shape attribute.

In [ ]:
a.shape = (3, 4)
a

array([[0.69699999, 0.40398593, 0.51616774, 0.09248855],
       [0.00874348, 0.47961266, 0.82526615, 0.07383346],
       [0.23389424, 0.76303897, 0.39756264, 0.23745441]])

In [ ]:
a.ndim

2

As you can see, this time it is the starting array to change shape and there is no object returned. The inverse operation is possible, that is, to convert a two-dimensional array into a one-dimensional array, through the ravel() function.

In [ ]:
a = a.ravel()
a

array([0.69699999, 0.40398593, 0.51616774, 0.09248855, 0.00874348,
       0.47961266, 0.82526615, 0.07383346, 0.23389424, 0.76303897,
       0.39756264, 0.23745441])

In [ ]:
a.ndim

1

In [ ]:
a.shape = (12)
a

array([0.69699999, 0.40398593, 0.51616774, 0.09248855, 0.00874348,
       0.47961266, 0.82526615, 0.07383346, 0.23389424, 0.76303897,
       0.39756264, 0.23745441])

In [ ]:
A

array([[0.69699999, 0.40398593, 0.51616774, 0.09248855],
       [0.00874348, 0.47961266, 0.82526615, 0.07383346],
       [0.23389424, 0.76303897, 0.39756264, 0.23745441]])

Another important operation is the transposition of a matrix that is an inversion of the columns with rows. NumPy provides this feature with the transpose() function.

In [ ]:
A.transpose()

array([[0.69699999, 0.00874348, 0.23389424],
       [0.40398593, 0.47961266, 0.76303897],
       [0.51616774, 0.82526615, 0.39756264],
       [0.09248855, 0.07383346, 0.23745441]])

### Reshaping an array using `reshape()`

In [ ]:
import numpy as np

# Create a 1D array
arr_1d = np.arange(12)
print(f"Original 1D array: {arr_1d}\nShape: {arr_1d.shape}\n")

# Reshape to a 2D array (3 rows, 4 columns)
arr_2d_reshaped = arr_1d.reshape(3, 4)
print(f"Reshaped 2D array (3x4):\n{arr_2d_reshaped}\nShape: {arr_2d_reshaped.shape}\n")

# Reshape to a 2D array (4 rows, 3 columns)
arr_2d_reshaped_2 = arr_1d.reshape(4, 3)
print(f"Reshaped 2D array (4x3):\n{arr_2d_reshaped_2}\nShape: {arr_2d_reshaped_2.shape}\n")

# Using -1 to automatically infer a dimension
arr_2d_inferred = arr_1d.reshape(2, -1) # 2 rows, columns inferred
print(f"Reshaped 2D array (2 rows, inferred columns):\n{arr_2d_inferred}\nShape: {arr_2d_inferred.shape}\n")

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped 2D array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Reshaped 2D array (4x3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)

Reshaped 2D array (2 rows, inferred columns):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape: (2, 6)



### Changing shape by assigning to the `.shape` attribute

In [ ]:
import numpy as np

arr = np.arange(15)
print(f"Original array: {arr}\nShape: {arr.shape}\n")

# Change the shape in-place
arr.shape = (3, 5)
print(f"Array after in-place shape change (3x5):\n{arr}\nShape: {arr.shape}\n")

# Change it back to 1D
arr.shape = (15,)
print(f"Array after changing back to 1D:\n{arr}\nShape: {arr.shape}\n")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Shape: (15,)

Array after in-place shape change (3x5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Shape: (3, 5)

Array after changing back to 1D:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Shape: (15,)



### Flattening an array using `ravel()`

In [ ]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"Original 2D array:\n{arr_2d}\nShape: {arr_2d.shape}\n")

# Flatten the array to 1D
arr_flattened = arr_2d.ravel()
print(f"Flattened array using ravel(): {arr_flattened}\nShape: {arr_flattened.shape}\n")

# Note: `ravel()` returns a view of the original array if possible,
# so changes to the flattened array might affect the original.
# Use `.flatten()` if you need an independent copy.

# Example of flatten() for an independent copy
arr_flattened_copy = arr_2d.flatten()
print(f"Flattened array using flatten() (copy): {arr_flattened_copy}\nShape: {arr_flattened_copy.shape}\n")

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

Flattened array using ravel(): [1 2 3 4 5 6 7 8 9]
Shape: (9,)

Flattened array using flatten() (copy): [1 2 3 4 5 6 7 8 9]
Shape: (9,)



### Transposing an array using `transpose()` or `.T`

In [ ]:
import numpy as np

arr_matrix = np.array([[1, 2, 3],
                       [4, 5, 6]])
print(f"Original Matrix:\n{arr_matrix}\nShape: {arr_matrix.shape}\n")

# Transpose using .transpose()
arr_transposed = arr_matrix.transpose()
print(f"Transposed Matrix using .transpose():\n{arr_transposed}\nShape: {arr_transposed.shape}\n")

# Transpose using the .T attribute (shorthand)
arr_transposed_T = arr_matrix.T
print(f"Transposed Matrix using .T attribute:\n{arr_transposed_T}\nShape: {arr_transposed_T.shape}\n")

# For higher-dimensional arrays, transpose can reorder axes
arr_3d = np.arange(24).reshape(2, 3, 4)
print(f"Original 3D array (2x3x4):\n{arr_3d}\nShape: {arr_3d.shape}\n")

arr_3d_transposed = arr_3d.transpose(1, 0, 2) # Swap axis 0 and 1
print(f"Transposed 3D array (axes 0 and 1 swapped):\n{arr_3d_transposed}\nShape: {arr_3d_transposed.shape}\n")

Original Matrix:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed Matrix using .transpose():
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)

Transposed Matrix using .T attribute:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)

Original 3D array (2x3x4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)

Transposed 3D array (axes 0 and 1 swapped):
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
Shape: (3, 2, 4)



#Array Manipulation

Often you need to create an array using already created arrays.

#Joining Arrays

You can merge multiple arrays together to form a new one that contains all of them. NumPy uses the concept of stacking, providing a number of functions in this regard. For example, you can run the vertical stacking with the vstack() function, which combines the second array as new rows of the first array. In this case you have a growth of the array in the vertical direction. By contrast, the hstack() function performs horizontal stacking; that is, the second array is added to the columns of the first array.

In [ ]:
A = np.ones((3, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
B = np.zeros((3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.vstack((A, B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

Two other functions performing stacking between multiple arrays are column_stack() and row_stack(). These functions operate differently than the two previous functions. Generally these functions are used with one-dimensional arrays that are stacked as columns or rows in order to form a new twodimensional array.

In [ ]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [ ]:
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
np.row_stack((a, b, c))

/tmp/ipykernel_892/3069552908.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b, c))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Splitting Arrays
NumPy provides functions to split arrays into smaller arrays. `np.split()`, `np.hsplit()`, and `np.vsplit()` are commonly used for this purpose.

In [ ]:
import numpy as np

arr_to_split = np.arange(16).reshape(4, 4)
print(f"Original Array for Splitting:\n{arr_to_split}\n")

# Split array into 4 equal sub-arrays along axis 0 (rows)
# np.split(array, num_sections_or_indices, axis=0)
split_rows = np.split(arr_to_split, 4, axis=0)
print(f"Split into 4 sub-arrays (rows):\n{split_rows[0]}\n{split_rows[1]}\n{split_rows[2]}\n{split_rows[3]}\n")

# Horizontally split (column-wise) into 2 equal sub-arrays
h_split_arrays = np.hsplit(arr_to_split, 2) # Equivalent to np.split(arr_to_split, 2, axis=1)
print(f"Horizontally split into 2 sub-arrays:\n{h_split_arrays[0]}\n{h_split_arrays[1]}\n")

# Vertically split (row-wise) into 2 equal sub-arrays
v_split_arrays = np.vsplit(arr_to_split, 2) # Equivalent to np.split(arr_to_split, 2, axis=0)
print(f"Vertically split into 2 sub-arrays:\n{v_split_arrays[0]}\n{v_split_arrays[1]}\n")

# Splitting at specific indices
arr_1d_split = np.arange(10)
print(f"Original 1D array: {arr_1d_split}\n")
split_at_indices = np.split(arr_1d_split, [3, 7]) # Split before index 3 and before index 7
print(f"Split at indices [3, 7]: {split_at_indices}\n")

Original Array for Splitting:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Split into 4 sub-arrays (rows):
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]

Horizontally split into 2 sub-arrays:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Vertically split into 2 sub-arrays:
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]

Original 1D array: [0 1 2 3 4 5 6 7 8 9]

Split at indices [3, 7]: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]



### Adding and Removing Elements
NumPy offers functions to add or remove elements from arrays, though these operations typically return a new array rather than modifying in-place, especially for `np.append`, `np.insert`, and `np.delete`.

In [ ]:
import numpy as np

original_arr = np.array([1, 2, 3])
print(f"Original array: {original_arr}\n")

# np.append(array, values, axis=None)
# Appending elements to a 1D array
appended_arr = np.append(original_arr, [4, 5])
print(f"Array after appending [4, 5]: {appended_arr}\n")

# For 2D arrays, you need to specify the axis
arr_2d = np.array([[1, 2], [3, 4]])
print(f"Original 2D array:\n{arr_2d}\n")

# Append a row (axis=0)
appended_row = np.append(arr_2d, [[5, 6]], axis=0)
print(f"2D array after appending row [[5, 6]]:\n{appended_row}\n")

# Append a column (axis=1)
appended_col = np.append(arr_2d, [[7], [8]], axis=1)
print(f"2D array after appending column [[7], [8]]:\n{appended_col}\n")

# np.insert(array, obj, values, axis=None)
# Insert element(s) at a specific index
inserted_arr = np.insert(original_arr, 1, 99) # Insert 99 at index 1
print(f"Array after inserting 99 at index 1: {inserted_arr}\n")

# Insert a row into a 2D array
inserted_row_2d = np.insert(arr_2d, 1, [0, 0], axis=0) # Insert [0,0] at row index 1
print(f"2D array after inserting row [0, 0] at index 1:\n{inserted_row_2d}\n")

# Insert a column into a 2D array
inserted_col_2d = np.insert(arr_2d, 1, [0, 0], axis=1) # Insert [0,0] at column index 1
print(f"2D array after inserting col [0, 0] at index 1:\n{inserted_col_2d}\n")

# np.delete(array, obj, axis=None)
# Delete element(s) at a specific index or slice
deleted_arr = np.delete(appended_arr, 2) # Delete element at index 2
print(f"Array after deleting element at index 2 (from appended_arr): {deleted_arr}\n")

# Delete a column from a 2D array
deleted_col_2d = np.delete(arr_2d, 0, axis=1) # Delete column at index 0
print(f"2D array after deleting column at index 0:\n{deleted_col_2d}\n")


# Delete a row from a 2D array
deleted_row_2d = np.delete(arr_2d, 0, axis=0) # Delete row at index 0
print(f"2D array after deleting row at index 0:\n{deleted_row_2d}\n")

Original array: [1 2 3]

Array after appending [4, 5]: [1 2 3 4 5]

Original 2D array:
[[1 2]
 [3 4]]

2D array after appending row [[5, 6]]:
[[1 2]
 [3 4]
 [5 6]]

2D array after appending column [[7], [8]]:
[[1 2 7]
 [3 4 8]]

Array after inserting 99 at index 1: [ 1 99  2  3]

2D array after inserting row [0, 0] at index 1:
[[1 2]
 [0 0]
 [3 4]]

2D array after inserting col [0, 0] at index 1:
[[1 0 2]
 [3 0 4]]

Array after deleting element at index 2 (from appended_arr): [1 2 4 5]

2D array after deleting column at index 0:
[[2]
 [4]]

2D array after deleting row at index 0:
[[3 4]]



### Resizing Arrays
`np.resize()` allows you to create a new array with a specified shape. If the new array is larger, it will fill new elements by repeating the existing array's contents. If smaller, it truncates. Be aware that `np.resize()` is generally less common for in-place modification compared to `arr.resize()` which can modify an array in-place, but has restrictions (e.g., requires no other references to the array).

In [ ]:
import numpy as np

original_arr = np.array([1, 2, 3])
print(f"Original array: {original_arr}\n")

# Resize to a larger shape (elements will repeat)
resized_larger = np.resize(original_arr, (6,))
print(f"Resized to larger (repeats elements): {resized_larger}\n")

# Resize to a smaller shape (elements will be truncated)
resized_smaller = np.resize(original_arr, (2,))
print(f"Resized to smaller (truncates elements): {resized_smaller}\n")

arr_2d_resize = np.array([[1, 2], [3, 4]])
print(f"Original 2D array:\n{arr_2d_resize}\n")

# Resize a 2D array
resized_2d = np.resize(arr_2d_resize, (3, 3))
print(f"Resized 2D array (3x3):\n{resized_2d}\n")

Original array: [1 2 3]

Resized to larger (repeats elements): [1 2 3 1 2 3]

Resized to smaller (truncates elements): [1 2]

Original 2D array:
[[1 2]
 [3 4]]

Resized 2D array (3x3):
[[1 2 3]
 [4 1 2]
 [3 4 1]]



#Splitting Arrays

First you saw how to assemble multiple arrays to each other through the operation of stacking. Now you will see the opposite operation, that is, to divide an array into several parts. In NumPy, to do this you will use splitting. Here too, you have a set of functions that work both horizontally with the hsplit() function and vertically with the vsplit() function.

In [ ]:
import numpy as np
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Thus, if you want to split the array horizontally, meaning the width of the array divided into two parts, the 4x4 matrix A will be split into two 2x4 matrices.

In [ ]:
[B,C] = np.hsplit(A, 2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
[B,C] = np.vsplit(A, 2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

A more complex command is the split() function, which allows you to split the array into nonsymmetrical parts. In addition, passing the array as an argument, you have also to specify the indexes of the parts to be divided. If you use the option axis = 1, then the indexes will be those of the columns; if instead the option is axis = 0, then they will be the row indexes.

For example, if you want to divide the matrix into three parts, the first of which will include the first column, the second will include the second and the third column, and the third will include the last column, then you must specify three indexes in the following way.

In [ ]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
[A1,A2,A3] = np.split(A,[1,3],axis=1)

In [ ]:
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [ ]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [ ]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
[A1,A2,A3] = np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [ ]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A3

array([[12, 13, 14, 15]])

#Copies or Views of Objects

As you may have noticed with NumPy, especially when you are performing operations or manipulations on the array, you can have as a return value either a copy or a view of the array. In NumPy, all assignments do not produce copies of arrays, nor any element contained within them.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a
b


array([1, 2, 3, 4])

In [ ]:
a[2] = 0
b

array([1, 2, 0, 4])

If you assign one array a to another array b, actually you are not doing a copy but b is just another way to call array a. In fact, by changing the value of the third element you change the third value of b too. When you perform the slicing of an array, actually the object returned is only a view of the original array.

In [ ]:
c = a[0:2]
c



array([1, 2])

In [ ]:
a[0] = 0
c

array([0, 2])

As you can see, even with the slicing, you are actually pointing to the same object. If you want to generate a complete copy and distinct array you can use the copy() function.

In [ ]:
a = np.array([1, 2, 3, 4])
c = a.copy()
c


array([1, 2, 3, 4])

In [ ]:
a[0] = 0
print(a)
print(c)


[0 2 3 4]
[1 2 3 4]


Here, even after `a[0]` is changed to 0, `c` (which was created using `a.copy()`) remains `[1, 2, 3, 4]`, demonstrating that `c` is a distinct, independent copy of `a` at the time of its creation.