NumPy, short for 'Numerical Python', is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently. Think of it like a super-powered list that can handle numbers much faster and with more advanced operations, especially useful for tasks in data science, machine learning, and scientific computing.



#Ndarray: The Heart of the Library

The whole NumPy library is based on one main object: ndarray (which stands for N-dimensional array). This object is a multidimensional homogeneous array with a predetermined number of items: homogeneous because virtually all the items within it are of the same type and the same size. In fact, the data type is specified by another NumPy object called dtype (data-type); each ndarray is associated with only one type of dtype.

The number of the dimensions and items in an array is defined by its shape, a tuple of N-positive integers that specifies the size for each dimension. The dimensions are defined as axes and the number of axes as rank.

Moreover, another peculiarity of NumPy arrays is that their size is fixed, that is, once you defined their size at the time of creation, it remains unchanged. This behavior is different from Python lists, which can grow or shrink in size.



In [ ]:
import math

In [ ]:
math.pi

3.141592653589793

In [ ]:
a=[1,2,3,4]

In [ ]:
type(a)

list

In [ ]:
import numpy as np

In [ ]:
#To define a new ndarray, the easiest way is to use the array() function, passing a Python list containing the elements to be included in it as an argument.

a = np.array([1, 2, 3])
a


array([1, 2, 3])

In [ ]:
#You can easily check that a newly created object is an ndarray, passing the new variable to the type() function.
type(a)

numpy.ndarray

In [ ]:
#In order to know the associated dtype to the just created ndarray, you have to use the dtype attribute.
a.dtype

dtype('int64')

The just-created array has one axis, and then its rank is 1, while its shape should be (3,1). To obtain these values from the corresponding array it is sufficient to use the ndim attribute for getting the axes, the size attribute to know the array length, and the shape attribute to get its shape.

In [ ]:
a.ndim

1

a.ndim (1): This tells you the number of dimensions (or axes) the array has. For array([1, 2, 3]), it's a one-dimensional array, so ndim is 1.

In [ ]:
a.size

3

a.size (3): This indicates the total number of elements in the array. In array([1, 2, 3]), there are three elements (1, 2, and 3), so size is 3.

In [ ]:
a.shape

(3,)

a.shape ((3,)): This returns a tuple representing the size of the array in each dimension. For our one-dimensional array, the shape is (3,), meaning it has 3 elements along its single dimension. If it were a 2x3 array, the shape would be (2, 3).

What you have just seen is the simplest case that is a one-dimensional array. But the use of arrays can be easily extended to the case with several dimensions. For example, if you define a two-dimensional array 2x2:

In [ ]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [ ]:
print(b)

[[1.3 2.4]
 [0.3 4.1]]


In [ ]:
b.dtype

dtype('float64')

In [ ]:
b.ndim

2

b.ndim (2): This indicates that array b has two dimensions. This is because it's a matrix with rows and columns.

In [ ]:
b.size

4

b.size (4): This means the array b contains a total of 4 elements (1.3, 2.4, 0.3, and 4.1).

In [ ]:
b.shape

(2, 2)

b.shape ((2, 2)): This tuple tells you the size of each dimension. The first 2 indicates that there are 2 rows, and the second 2 indicates that there are 2 columns, forming a 2x2 matrix.

This array has rank 2, since it has two axis, each of length 2.

Another important attribute is itemsize, which can be used with ndarray objects. It defines the size in bytes of each item in the array

In [ ]:
b.itemsize

8

The b.itemsize result of 8 means that each element (item) in the array b occupies 8 bytes of memory. Since b contains floating-point numbers (dtype('float64')), and a float64 typically uses 8 bytes, this result is consistent.

#Data Types supported by NumPy

In [ ]:
import numpy as np

# Get all supported scalar types
all_numpy_dtypes = sorted(list(np.sctypeDict.keys()))

# Print them in a more readable format
print("Supported NumPy Data Types:\n")
for i, dtype in enumerate(all_numpy_dtypes):
    print(f"- {dtype}")

Supported NumPy Data Types:

- a
- bool
- bool_
- byte
- bytes
- bytes_
- cdouble
- clongdouble
- complex
- complex128
- complex256
- complex64
- csingle
- datetime64
- double
- float
- float128
- float16
- float32
- float64
- half
- int
- int16
- int32
- int64
- int8
- int_
- intc
- intp
- long
- longdouble
- longlong
- object
- object_
- short
- single
- str
- str_
- timedelta64
- ubyte
- uint
- uint16
- uint32
- uint64
- uint8
- uintc
- uintp
- ulong
- ulonglong
- unicode
- ushort
- void


In [ ]:
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8',
            'uint8',
            'int16',
            'uint16',
            'int or int32',
            'uint32',
            'int64',
            'uint64',
            'float16',
            'float32',
            'float or float64',
            'float128',
            'complex64',
            'complex or complex128',
            'bool',
            'object',
            'string_',
            'unicode_',
        ],

        'Type Code': [
            'i1',
            'u1',
            'i2',
            'u2',
            'i4 or i',
            'u4',
            'i8',
            'u8',
            'f2',
            'f4 or f',
            'f8 or d',
            'f16 or g',
            'c8',
            'c16',
            None,
            'O',
            'S',
            'U',
        ]
    }
)

dtypes

,Type,Type Code
0,int8,i1
1,uint8,u1
2,int16,i2
3,uint16,u2
4,int or int32,i4 or i
5,uint32,u4
6,int64,i8
7,uint64,u8
8,float16,f2
9,float32,f4 or f


#Create an Array

To create a new array you can follow different paths. The most common is the one you saw in the previous section through a list or sequence of lists as arguments to the array() function.

In [ ]:
c = np.array([[1, 2, 3],[4, 5, 6]])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

The array() function in addition to the lists can accept even tuples and sequences of tuples.

In [ ]:
d = np.array(((1, 2, 3),(4, 5, 6)))

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d.ndim

2

In [ ]:
d.shape

(2, 3)

In [ ]:
d.size

6

Also, even sequences of tuples and lists interconnected make no difference.

In [ ]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])

In [ ]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

You've already seen this method. The `np.array()` function is the most common way to create an array from a Python list or tuple. NumPy automatically infers the data type.

In [ ]:
# From a list
list_array = np.array([1, 2, 3, 4, 5])
print("Array from list:", list_array)
print("Data type:", list_array.dtype)

# From a list of lists (2D array)
list_of_lists_array = np.array([[10, 20], [30, 40]])
print("\nArray from list of lists:\n", list_of_lists_array)
print("Shape:", list_of_lists_array.shape)

# From a tuple
tuple_array = np.array((6, 7, 8))
print("\nArray from tuple:", tuple_array)

# From a tuple of tuples (2D array)
tuple_of_tuples_array = np.array(((50, 60), (70, 80)))
print("\nArray from tuple of tuples:\n", tuple_of_tuples_array)

Array from list: [1 2 3 4 5]
Data type: int64

Array from list of lists:
 [[10 20]
 [30 40]]
Shape: (2, 2)

Array from tuple: [6 7 8]

Array from tuple of tuples:
 [[50 60]
 [70 80]]


Types of Data

In [ ]:
g= np.array([['a', 'b'],['c', 'd']])

In [ ]:
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [ ]:
g.dtype

dtype('<U1')

In [ ]:
g.dtype.name

'str32'

Data types can be defined at creating the numpy array and converted to other types later.

You can use either type, type code or np dot methods to define the data type of an array, but when you use np dot method to define the data type, it can only follow type rather than type code.

In [ ]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3], dtype='f4')
arr.dtype

dtype('float32')

In [ ]:
# Identical to the above
arr = np.array([1,2,3], dtype='float32')
arr.dtype

dtype('float32')

In [ ]:
arr = np.array([1+2j, 3-4j], dtype=np.complex64)
arr.dtype

dtype('complex64')

In [ ]:
# Identical to the above
arr = np.array([1+2j, 3-4j], dtype='c8')
arr.dtype

dtype('complex64')

In [ ]:
# ERROR
arr = np.array([1+2j, 3-4j], dtype=np.c8)
arr.dtype

AttributeError: module 'numpy' has no attribute 'c8'

#Type Conversion

astype method: convert the data type of an array to other data types.

Notice that astype returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

In [ ]:
arr = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32)
print('Data Type After Conversion: ' + str(arr.dtype))

Original Data Type: int16
Data Type After Conversion: float32


In [ ]:
# An example of integer overflow at downcasting
arr = np.array([126,127,256], dtype='int16')
print('np array before type conversion: ' + str(arr))

# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))

np array before type conversion: [126 127 256]
np array after type conversion: [126 127   0]


In [ ]:
import numpy as np

# 1. Create a float32 array
float_arr = np.array([1.5, 2.7, 3.2], dtype=np.float32)

# 2. Print float_arr and its dtype
print(f"float_arr: {float_arr}")
print(f"float_arr dtype: {float_arr.dtype}\n")

# 3. Create an int8 array by first creating with a larger dtype and then converting
# (Original values [100, 150, 200] cause OverflowError if created directly as int8)
# We'll create it as int16 first to allow the values, then convert to int8 to show wraparound
temp_int_arr = np.array([100, 150, 200], dtype=np.int16) # Use int16 to hold values initially
int_arr = temp_int_arr.astype(np.int8) # Convert to int8 to demonstrate overflow

# 4. Print int_arr and its dtype. Explain why 200 appears differently.
print(f"int_arr: {int_arr}")
print(f"int_arr dtype: {int_arr.dtype}\n")
print("Explanation for int_arr: The int8 data type can only hold values from -128 to 127. When larger values like 150 and 200 are converted to int8, they 'overflow' and wrap around. For 150, it wraps from 127 to -128, then continues, resulting in -106 (150 - 256 = -106, as 256 is the total range of int8). For 200, it becomes -56 (200 - 256 = -56).")

# 5. Convert float_arr to an array of integers
converted_int_arr = float_arr.astype(int)
print(f"converted_int_arr: {converted_int_arr}")
print(f"converted_int_arr dtype: {converted_int_arr.dtype}")

float_arr: [1.5 2.7 3.2]
float_arr dtype: float32

int_arr: [ 100 -106  -56]
int_arr dtype: int8

Explanation for int_arr: The int8 data type can only hold values from -128 to 127. When larger values like 150 and 200 are converted to int8, they 'overflow' and wrap around. For 150, it wraps from 127 to -128, then continues, resulting in -106 (150 - 256 = -106, as 256 is the total range of int8). For 200, it becomes -56 (200 - 256 = -56).
converted_int_arr: [1 2 3]
converted_int_arr dtype: int64


In [ ]:
import numpy as np

# 1. Create a float32 array
float_arr = np.array([1.5, 2.7, 3.2], dtype=np.float32)

# 2. Print float_arr and its dtype
print(f"float_arr: {float_arr}")
print(f"float_arr dtype: {float_arr.dtype}\n")

# 3. Create an int8 array by first creating with a larger dtype and then converting
# (Original values [100, 150, 200] cause OverflowError if created directly as int8)
# We'll create it as int16 first to allow the values, then convert to int8 to show wraparound
temp_int_arr = np.array([100, 150, 200], dtype=np.int16) # Use int16 to hold values initially
int_arr = temp_int_arr.astype(np.int8) # Convert to int8 to demonstrate overflow

# 4. Print int_arr and its dtype. Explain why 200 appears differently.
print(f"int_arr: {int_arr}")
print(f"int_arr dtype: {int_arr.dtype}\n")
print("Explanation for int_arr: The int8 data type can only hold values from -128 to 127. When larger values like 150 and 200 are converted to int8, they 'overflow' and wrap around. For 150, it wraps from 127 to -128, then continues, resulting in -106 (150 - 256 = -106, as 256 is the total range of int8). For 200, it becomes -56 (200 - 256 = -56).")

# 5. Convert float_arr to an array of integers
converted_int_arr = float_arr.astype(int)
print(f"converted_int_arr: {converted_int_arr}")
print(f"converted_int_arr dtype: {converted_int_arr.dtype}")

float_arr: [1.5 2.7 3.2]
float_arr dtype: float32

int_arr: [ 100 -106  -56]
int_arr dtype: int8

Explanation for int_arr: The int8 data type can only hold values from -128 to 127. When larger values like 150 and 200 are converted to int8, they 'overflow' and wrap around. For 150, it wraps from 127 to -128, then continues, resulting in -106 (150 - 256 = -106, as 256 is the total range of int8). For 200, it becomes -56 (200 - 256 = -56).
converted_int_arr: [1 2 3]
converted_int_arr dtype: int64


#String and Unicode Data Type

The string_ and unicode_ data types are all implicitly fixed-length.

The length of the string is given by their type code appended with a number. For example, S3 represents string of length 3; U10 represents unicode of length 10. Otherwise, the default length is the length of the longest string in the array.

If the length of a string in the array is shorter than the length of the data type defined or converted to, the string will be truncated.

In [ ]:
# An example of truncated string
s = np.array(['abc', 'defg'], dtype='S3')
print(s)

# An example of truncated unicode
s = np.array(['abcd', 'efghi'], dtype='U3')
print(s)

[b'abc' b'def']
['abc' 'efg']


The output [b'abc' b'def'] is a NumPy array containing byte strings. In NumPy, when you specify dtype='S3', it creates a byte string array where each element is allocated exactly 3 bytes.

b'abc': This means the string 'abc' is stored as a byte string. The b prefix indicates a byte literal.
b'def': The original string was 'defg'. However, because the dtype was specified as 'S3' (meaning a fixed length of 3 bytes), the string 'defg' was truncated to 'def'. NumPy simply cut off the excess characters to fit the defined length.

The last code cell showed examples of string and Unicode truncation due to fixed-length data types. When you create a NumPy array with dtype='S3', it means each string element in the array is allocated exactly 3 bytes (for byte strings). If an input string is longer than 3 characters, it gets truncated. Similarly, for dtype='U3', each Unicode string element is allocated space for 3 characters, and longer strings are also truncated.

s = np.array(['abc', 'defg'], dtype='S3') resulted in [b'abc' b'def']. The string 'defg' was truncated to 'def' because the dtype='S3' specified a maximum length of 3 characters.
s = np.array(['abcd', 'efghi'], dtype='U3') resulted in ['abc' 'efg']. Here, 'abcd' became 'abc' and 'efghi' became 'efg' for the same reason: the dtype='U3' enforced a 3-character limit for Unicode strings.

#The dtype Option

The array() function does not accept a single argument. You have seen that each ndarray object is associated with a dtype object that uniquely defines the type of data that will occupy each item in the array. By default, the array() function is able to associate the most suitable type according to the values contained in the sequence of lists or tuples used. Actually, you can explicitly define the dtype using the dtype option as argument of the function.

In [ ]:
f = np.array([[1, 2, 3],[4, 5, 6]])
f

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#For example if you want to define an array with complex values you can use the dtype option as follows:
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

#Intrinsic Creation of an Array

The NumPy library provides a set of functions that generate the ndarrays with an initial content, created with some different values depending on the function. In fact, they allow a single line of code to generate large
amounts of data.

In [ ]:
#The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape argument. For example, to create a two-dimensional array 3x3:
l=np.zeros((3, 3))

In [ ]:
l

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
l.ndim

2

In [ ]:
l.size

9

In [ ]:
l.dtype

dtype('float64')

In [ ]:
#while the ones() function creates an array full of ones in a very similar way.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

By default, the two functions have created arrays with float64 data type. A feature that will be particularly useful is arange(). This function generates NumPy arrays with numerical sequences that respond to particular rules depending on the passed arguments. For example, if you want to generate a
sequence of values between 0 and 10, you will be passed only one argument to the function, that is the value with which you want to end the sequence.

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#If instead of starting from zero you want to start from another value, simply specify two arguments: the first is the starting value and the second is the final value.
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [ ]:
#It is also possible to generate a sequence of values with precise intervals between them. If the third argument of the arange() function is specified, this will represent the gap between a value and the next one in the sequence of values.
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [ ]:
#In addition, this third argument can also be a float.
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

But so far you have only created one-dimensional arrays. To generate two-dimensional arrays you can still continue to use the arange() function but combined with the reshape() function. This function divides a linear array in different parts in the manner specified by the shape argument.

In [ ]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Another function very similar to arange() is linspace(). This function still takes as its first two arguments the initial and end values of the sequence, but the third argument, instead of specifying the distance between one element and the next, defines the number of elements into which we want the interval
to be split.

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.linspace(0,10,4).reshape(2,2)

array([[ 0.        ,  3.33333333],
       [ 6.66666667, 10.        ]])

In [ ]:
np.linspace(0,10,5).reshape(2,2)

ValueError: cannot reshape array of size 5 into shape (2,2)

Finally, another method to obtain arrays already containing values is to fill them with random values. This is possible using the random() function of the numpy.random module. This function will generate an array with many elements as specified in the argument.

In [ ]:
np.random.random(3)

array([0.02044733, 0.49901534, 0.12827143])

In [ ]:
#The numbers obtained will vary with every run. To create a multidimensional array simply pass the size of the array as an argument.
np.random.random((3,3))

array([[0.6138305 , 0.06814811, 0.33598897],
       [0.11054121, 0.83263112, 0.33830982],
       [0.55448254, 0.33332121, 0.61781982]])