#Examples of Indexing and Slicing

In [ ]:
import numpy as np

# Create a 1D array for demonstration
arr_1d = np.arange(10, 20)
print(f"Original 1D array: {arr_1d}")

Original 1D array: [10 11 12 13 14 15 16 17 18 19]


### 1D Array Indexing: Single Elements

- **Positive Indexing**: `arr_1d[i]` gets the element at index `i` (starting from 0).
- **Negative Indexing**: `arr_1d[-i]` gets the element `i` positions from the end (e.g., `-1` is the last element).

In [ ]:
print(f"Element at index 3: {arr_1d[3]}")
print(f"Last element (index -1): {arr_1d[-1]}")
print(f"Second to last element (index -2): {arr_1d[-2]}")

Element at index 3: 13
Last element (index -1): 19
Second to last element (index -2): 18


### 1D Array Indexing: Multiple Elements (Fancy Indexing)

Pass a list or array of indices to select multiple non-contiguous elements.

In [ ]:
print(f"Elements at indices [0, 4, 8]: {arr_1d[[0, 4, 8]]}")

Elements at indices [0, 4, 8]: [10 14 18]


### 1D Array Indexing: Slicing

Slicing allows you to select a range of elements. The syntax is `[start:end:step]`.

- `start` is inclusive.
- `end` is exclusive.
- `step` defines the increment.

In [ ]:
print(f"Elements from index 2 up to (but not including) 7: {arr_1d[2:7]}")
print(f"Elements from the beginning up to index 5: {arr_1d[:5]}")
print(f"Elements from index 5 to the end: {arr_1d[5:]}")
print(f"Every second element: {arr_1d[::2]}")
print(f"Reversed array: {arr_1d[::-1]}")

Elements from index 2 up to (but not including) 7: [12 13 14 15 16]
Elements from the beginning up to index 5: [10 11 12 13 14]
Elements from index 5 to the end: [15 16 17 18 19]
Every second element: [10 12 14 16 18]
Reversed array: [19 18 17 16 15 14 13 12 11 10]


In [ ]:
name="python"
name[::-1]


'nohtyp'

In [ ]:
# Create a 2D array for demonstration
arr_2d = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])
print(f"Original 2D array:\n{arr_2d}")

Original 2D array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 2D Array Indexing: Single Elements

For 2D arrays (matrices), you provide `[row_index, column_index]`.

In [ ]:
print(f"Element at row 1, column 2: {arr_2d[1, 2]}")
print(f"Element at row 0, column 0: {arr_2d[0, 0]}")
print(f"Element at last row, first column: {arr_2d[-1, 0]}")

Element at row 1, column 2: 16
Element at row 0, column 0: 10
Element at last row, first column: 18


### 2D Array Indexing: Rows and Columns

- To select an entire row, specify only the row index.
- To select an entire column, use a colon `:` for the row index and specify the column index.

### 2D Array Indexing: Slicing

Slicing can be applied to both rows and columns simultaneously. For example, `[row_start:row_end, col_start:col_end]`.

In [ ]:
print(f"Subset of rows 0-1 and columns 1-2:\n{arr_2d[0:2, 1:3]}")
print(f"All rows, columns 0 and 2:\n{arr_2d[:, [0, 2]]}")
print(f"Rows 0 and 2, all columns:\n{arr_2d[[0, 2], :]}")

Subset of rows 0-1 and columns 1-2:
[[11 12]
 [15 16]]
All rows, columns 0 and 2:
[[10 12]
 [14 16]
 [18 20]]
Rows 0 and 2, all columns:
[[10 11 12 13]
 [18 19 20 21]]


In [ ]:
# Create a 2D array for demonstration
import numpy as np
arr_2d_new = np.array([
    [20, 21, 22, 23],
    [24, 25, 26, 27],
    [28, 29, 30, 31]
])
print(f"Original 2D array:\n{arr_2d_new}")

Original 2D array:
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
#Subset of rows 0-1 and columns 1-2:

arr_2d_new[0:2, 1:3]


array([[21, 22],
       [25, 26]])

In [ ]:
#Subset of rows 0-1 and columns 1-2:

arr_2d_new[1:3, 2:4]

array([[26, 27],
       [30, 31]])

In [ ]:
arr_2d_new[0:4,2:4]

array([[22, 23],
       [26, 27],
       [30, 31]])

In [ ]:
arr_2d_new[:,2:4]

array([[22, 23],
       [26, 27],
       [30, 31]])

In [ ]:
# Create a 2D array for demonstration
import numpy as np
arr_2d_new = np.array([
    [20, 21, 22, 23],
    [24, 25, 26, 27],
    [28, 29, 30, 31]
])
print(f"Original 2D array:\n{arr_2d_new}")

Original 2D array:
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
arr_2d_new[1:4,0:4]

array([[24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr_2d_new[1:4,:]

array([[24, 25, 26, 27],
       [28, 29, 30, 31]])

#Iterating an Array

In Python, the iteration of the items in an array is really very simple; you just need to use the for construct.

In [ ]:
import numpy as np

# Create a 1D array for iteration
array_1d = np.array([10, 20, 30, 40, 50])
print(f"Original 1D array: {array_1d}\n")

Original 1D array: [10 20 30 40 50]



In [ ]:
x="python"
for i in x:
  print(i)

p
y
t
h
o
n


### Iterating a 1D Array using a `for` loop

For a 1D array, a simple `for` loop iterates through each element directly.

In [ ]:
print("Iterating through 1D array elements:")
for element in array_1d:
    print(element)

Iterating through 1D array elements:
10
20
30
40
50


In [ ]:
# Create a 2D array for iteration
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"\nOriginal 2D array:\n{array_2d}\n")


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



### Iterating a 2D Array using a `for` loop

When iterating over a 2D array with a single `for` loop, it iterates over the *rows* of the array.

In [ ]:
print("Iterating through 2D array rows:")
for row in array_2d:
    print(row)

Iterating through 2D array rows:
[1 2 3]
[4 5 6]
[7 8 9]


### Iterating through Elements of a 2D Array (Nested `for` loops)

To access individual elements in a 2D array, you typically use nested `for` loops.

In [ ]:
print("Iterating through 2D array elements using nested loops:")
for row in array_2d:
    for element in row:
        print(element)

Iterating through 2D array elements using nested loops:
1
2
3
4
5
6
7
8
9


In [ ]:
import numpy as np

# Create a sample 2D array
array_2d = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])
print(f"Original 2D array:\n{array_2d}\n")

print("Extracting columns using a for loop:")
for col_idx in range(array_2d.shape[1]):
    column = array_2d[:, col_idx]
    print(f"Column {col_idx}: {column}")

Original 2D array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Extracting columns using a for loop:
Column 0: [10 14 18]
Column 1: [11 15 19]
Column 2: [12 16 20]
Column 3: [13 17 21]


### Iterating with `np.nditer()`

NumPy provides the `nditer` object for efficient and flexible iteration over arrays, especially for multi-dimensional arrays. By default, `nditer` iterates over elements in a C-style (row-major) order.

In [ ]:
print("Iterating through elements of a 2D array using np.nditer():")
for element in np.nditer(array_2d):
    print(element)

Iterating through elements of a 2D array using np.nditer():
10
11
12
13
14
15
16
17
18
19
20
21


#### Controlling Iteration Order

You can specify the iteration order using `order` flags like `'F'` for Fortran-style (column-major) order.

In [ ]:
print("Iterating in Fortran-style (column-major) order with np.nditer():")
for element in np.nditer(array_2d, order='F'):
    print(element)

Iterating in Fortran-style (column-major) order with np.nditer():
10
14
18
11
15
19
12
16
20
13
17
21


#### Modifying Array Elements During Iteration

To modify array elements during iteration, you need to use the `'readwrite'` flag.

In [ ]:
print("Modifying elements during iteration with np.nditer() and 'readwrite' flag:")
original_array = np.array([[1, 2], [3, 4]])
print(f"Original array:\n{original_array}")

for x in np.nditer(original_array, op_flags=['readwrite']):
    x[...] = x * 2 # Modify the element in place

print(f"Modified array:\n{original_array}")

Modifying elements during iteration with np.nditer() and 'readwrite' flag:
Original array:
[[1 2]
 [3 4]]
Modified array:
[[2 4]
 [6 8]]


### Iterating Over Multiple Arrays Simultaneously

You can iterate over multiple arrays at the same time using `np.nditer`.

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([10, 20, 30])

print("Iterating over two arrays simultaneously:")
for x, y in np.nditer([array1, array2]):
    print(f"Element from array1: {x}, Element from array2: {y}, Sum: {x+y}")

Iterating over two arrays simultaneously:
Element from array1: 1, Element from array2: 10, Sum: 11
Element from array1: 2, Element from array2: 20, Sum: 22
Element from array1: 3, Element from array2: 30, Sum: 33


If you want to launch an aggregate function that returns a value calculated for every single column or on every single row, there is an optimal way to makes that it will be entirely NumPy to manage the iteration: the apply_along_axis() function.

This function takes three arguments: the aggregate function, the axis on which to apply the iteration, and finally the array. If the option axis equals 0, then the iteration evaluates the elements column by column, whereas if the axis equals 1 then the iteration evaluates the elements row by row. For example, you
can calculate the average of the values for the first by column and then by row.

In [ ]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.apply_along_axis(np.mean, axis=0, arr=A)


array([13., 14., 15.])

In [ ]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

In [ ]:
def foo(x):
  return x/2

np.apply_along_axis(foo, axis=1, arr=A)


array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [ ]:
def foo(x):
  return x/2

np.apply_along_axis(foo, axis=0, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

### Boolean Indexing

Boolean indexing uses a boolean array to select elements. Only elements corresponding to `True` in the boolean array are selected.

In [ ]:
import numpy as np

# Create a 1D array for iteration
array_1d = np.array([10, 20, 30, 40, 50])
print(f"Original 1D array: {array_1d}\n")

Original 1D array: [10 20 30 40 50]



In [ ]:
# 1D array example
bool_mask_1d = (array_1d > 25)
print(f"1D array elements greater than 25: {array_1d[bool_mask_1d]}")

# 2D array example
bool_mask_1d_new = (array_1d % 3 == 0)
print(f"1D array elements that are divisible by 3: {array_1d[bool_mask_1d_new]}")

1D array elements greater than 25: [30 40 50]
1D array elements that are divisible by 3: [30]


### What are Conditional and Boolean Arrays?

A **conditional array** (or boolean array/mask) is a NumPy array where each element is a boolean value (`True` or `False`). These arrays are typically generated by applying a conditional expression (e.g., `arr > 5`, `arr % 2 == 0`) to an existing NumPy array. The resulting boolean array has the same shape as the original, with `True` wherever the condition is met and `False` otherwise.

They are primarily used for:
1.  **Filtering/Selecting**: Extracting elements that meet a certain condition.
2.  **Modifying**: Changing values of elements that meet a certain condition.
3.  **Counting**: Determining how many elements satisfy a condition.

In [ ]:
import numpy as np

# Create a sample 1D array
arr_1d = np.array([1, 5, 10, 15, 20, 25, 30])
print(f"Original 1D array: {arr_1d}")

# Create a sample 2D array
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(f"\nOriginal 2D array:\n{arr_2d}")

Original 1D array: [ 1  5 10 15 20 25 30]

Original 2D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


### Use Case 1: Filtering/Selecting Elements

This is the most common use case. You can select elements from an array by passing a boolean array of the same shape as the index. Only elements where the boolean array is `True` will be selected.

In [ ]:
# 1D array: Select elements greater than 10
condition_1d = arr_1d > 10
print(f"Boolean mask (arr_1d > 10): {condition_1d}")
filtered_1d = arr_1d[condition_1d]
print(f"Filtered 1D array (elements > 10): {filtered_1d}\n")

# You can also do this in one line
print(f"Elements equal to 25: {arr_1d[arr_1d == 25]}\n")

Boolean mask (arr_1d > 10): [False False False  True  True  True  True]
Filtered 1D array (elements > 10): [15 20 25 30]

Elements equal to 25: [25]



In [ ]:
# 1D array: Select elements greater than 10
condition_1d = arr_1d == 25
print(f"Boolean mask (arr_1d ==25): {condition_1d}")
filtered_1d = arr_1d[condition_1d]
print(f"Filtered 1D array (elements == 25): {filtered_1d}\n")

Boolean mask (arr_1d ==25): [False False False False False  True False]
Filtered 1D array (elements == 25): [25]



In [ ]:
# 2D array: Select elements greater than 50
condition_2d = arr_2d > 50
print(f"Boolean mask (arr_2d > 50):\n{condition_2d}")
filtered_2d = arr_2d[condition_2d]
print(f"Filtered 2D array (elements > 50): {filtered_2d}\n")

# Note: When filtering a 2D array with a boolean mask, the result is always a 1D array.

Boolean mask (arr_2d > 50):
[[False False False]
 [False False  True]
 [ True  True  True]]
Filtered 2D array (elements > 50): [60 70 80 90]



### Use Case 2: Modifying Elements

Boolean arrays can be used to selectively modify elements in an array based on a condition.

In [ ]:
arr_mod = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Original array for modification: {arr_mod}")

# Change all elements greater than 5 to 0
arr_mod[arr_mod > 5] = 0
print(f"Array after modifying elements > 5 to 0: {arr_mod}\n")

arr_mod_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"Original 2D array for modification:\n{arr_mod_2d}")

# Set even numbers to -1
arr_mod_2d[arr_mod_2d % 2 == 0] = -1
print(f"2D array after setting even numbers to -1:\n{arr_mod_2d}")

Original array for modification: [ 1  2  3  4  5  6  7  8  9 10]
Array after modifying elements > 5 to 0: [1 2 3 4 5 0 0 0 0 0]

Original 2D array for modification:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D array after setting even numbers to -1:
[[ 1 -1  3]
 [-1  5 -1]
 [ 7 -1  9]]


### Use Case 3: Counting Elements

Since `True` evaluates to 1 and `False` to 0 in numerical contexts, you can easily count elements satisfying a condition by summing the boolean array.

In [ ]:
arr_count = np.array([1, 2, 5, 8, 10, 11, 15, 20])
print(f"Array for counting: {arr_count}")

# Count elements greater than 10
count_gt_10 = np.sum(arr_count > 10)
print(f"Number of elements greater than 10: {count_gt_10}\n")

# Count even numbers in a 2D array
arr_count_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"2D Array for counting:\n{arr_count_2d}")
count_even_2d = np.sum(arr_count_2d % 2 == 0)
print(f"Number of even elements in 2D array: {count_even_2d}")

Array for counting: [ 1  2  5  8 10 11 15 20]
Number of elements greater than 10: 3

2D Array for counting:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of even elements in 2D array: 4


### Use Case 4: Combining Multiple Conditions

You can combine multiple conditions using logical operators (`&` for AND, `|` for OR, `~` for NOT). Remember to wrap individual conditions in parentheses.

In [ ]:
arr_combined = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(f"Original array: {arr_combined}")

# Select elements greater than 20 AND less than 60
condition_combined = (arr_combined > 20) & (arr_combined < 60)
print(f"Boolean mask ((arr > 20) & (arr < 60)): {condition_combined}")
filtered_combined = arr_combined[condition_combined]
print(f"Filtered elements: {filtered_combined}\n")

# Select elements divisible by 3 OR greater than 70
condition_or = (arr_combined % 3 == 0) | (arr_combined > 70)
print(f"Boolean mask ((arr % 3 == 0) | (arr > 70)): {condition_or}")
filtered_or = arr_combined[condition_or]
print(f"Filtered elements: {filtered_or}")

Original array: [10 20 30 40 50 60 70 80]
Boolean mask ((arr > 20) & (arr < 60)): [False False  True  True  True False False False]
Filtered elements: [30 40 50]

Boolean mask ((arr % 3 == 0) | (arr > 70)): [False False  True False False  True False  True]
Filtered elements: [30 60 80]
